### ISSUE TITLE
Paths looks like to not be properly resolved with tilde

### ISSUE THREAD

**Issue by TorstenDittmann** [byawitz/ggh#5]
<img width="780" alt="Bildschirmfoto 2024-09-09 um 12 42 12" src="https://github.com/user-attachments/assets/b5f53588-6f3f-4b88-a1c5-037b5451cd6c">

content of `.ssh/config`:

```sh
Include ~/.orbstack/ssh/config
```

**Comment by byawitz** [comment]
Fixed in #7
